spring:
  # 本地 H2 数据库配置
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demotwo-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 123456
  # H2 控制台（本地可访问：http://localhost:8080/h2-console）
  h2:
    console:
      enabled: true
      path: /h2-console
  # JPA 适配 H2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 本地开发显示 SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false