spring:
  # Render PostgreSQL 配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL} # Render 注入的数据库 URL
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  # 关闭 H2 控制台
  h2:
    console:
      enabled: false
  # JPA 适配 PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false